name: Build and Push Docker Image

on: push

jobs:
  secret-generator:
    runs-on: ubuntu-latest
    outputs:
      handle: ${{ steps.generate-secret.outputs.handle }}
    steps:
      - uses: actions/checkout@v2

      - name: generate secret
        id: generate-secret
        run: |
          GENERATED_SECRET=$((RANDOM))
          echo "::add-mask::$GENERATED_SECRET"
          echo "handle=$GENERATED_SECRET" >> "$GITHUB_OUTPUT"

  build-and-push:
    runs-on: ubuntu-latest
    needs: secret-generator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wireguard-with-password:latest
        env:
          PASSWORD: ${{ needs.secret-generator.outputs.handle }}
